apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: host-routing 
  namespace: default
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/affinity: 'cookie'
spec:
  rules:
  - host: elasticsearch.default.svc.cluster.local
    http:
      nodePort: '31183'
      paths:
      - backend:
          serviceName: kibana
          servicePort: '5601'

---
apiVersion: v1
kind: Service
metadata:
  name: host-routing-stats
  labels:
    app: voyager-stats
spec:
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 56789
      targetPort: 56789
      nodePort: 30315
  selector:
    origin: voyager
    origin-name: host-routing
