apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: host-routing
  namespace: default
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/affinity: 'cookie'
spec:
  rules:
  - host: elasticsearch.default.svc.cluster.local
    http:
      nodePort: '31183'
      paths:
      - backend:
          serviceName: kibana
          servicePort: '5601'
