apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    weblogic.sha256: 96c43f64218a2da3d3a19a3e7a9f32bf37acd5402ae47ba24aa69b6742cbc4ae
  labels:
    serviceType: SERVER
    weblogic.createdByOperator: "true"
    weblogic.domainName: weblogic-fourteen
    weblogic.domainUID: weblogic-fourteen
    weblogic.resourceVersion: domain-v2
    weblogic.serverName: admin-server
  name: weblogic-fourteen-admin-server
  namespace: default
  resourceVersion: "11783723"
  selfLink: /api/v1/namespaces/default/services/weblogic-fourteen-admin-server
spec:
#  clusterIP: None
  ports:
  - name: t3channel
    port: 30012
    protocol: TCP
    targetPort: 30012
  - name: default
    port: 7001
    protocol: TCP
    targetPort: 7001
  publishNotReadyAddresses: true
  selector:
    weblogic.createdByOperator: "true"
    weblogic.domainUID: weblogic-fourteen
    weblogic.serverName: admin-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
