# Copyright (c) 2018, 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: soa-pvc
  namespace: soa-ns
  labels:
    weblogic.resourceVersion: domain-v2
    # weblogic.domainUID: 
spec:
  storageClassName: soa-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
